name: animation_practice1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # IMPORTANT: Make sure you list your fonts directory in assets!
    - assets/fonts/
    - assets/pngs/

  fonts:
    - family: Formula
      fonts:
        # FormulaCondensed Light (Weight 300)
        - asset: assets/fonts/FormulaCondensed-Light.otf
          weight: 300 
          
        # FormulaCondensed Bold (Weight 700)
        - asset: assets/fonts/FormulaCondensed-Bold.otf
          weight: 700 